services:
  dock-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
