name: Testing
run-name: Running tests on branch ${{ github.ref }}
on: [push]
jobs:
  pushed_branch_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Checking docker version
        run: docker --version

      - name: Building docker image
        run: docker build -t nishantni8/dock_frontend:latest -f Dockerfile.dev .

      - name: Building container and running tests
        run: docker run nishantni8/dock_frontend:latest npm run test:coverage